### PR TITLE
`outputs` do not inherit `build/noarch` parameter

### PR DESCRIPTION
**Pull request by kenodegard**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

These new packages were accidentally not `noarch` packages since `outputs` do not inherit from `build/noarch`.

### CODE REVIEW

**Comment by kenodegard** [comment]
@conda-forge-admin, please rerender

**Comment by kenodegard** [comment]
@conda-forge-admin, please rerender

**Review by nsoranzo — APPROVED** [review]
Do we also need to mark the arch-specific packages that have already been built as broken, like e.g. https://github.com/conda-forge/admin-requests/pull/726/ ?

**Comment by kenodegard** [comment]
@nsoranzo not necessary (the arch specific ones work fine) but I'll do that to cleanup

**Pull request merged**
